### ISSUE TITLE
Weston Embedded on Teensy 4.x

### ISSUE THREAD

**Issue by JPB1JPB1** [weston-embedded/uC-CPU#4]
Please, any weston embedded code available to test on high performance low power Teensy 4.0 and 4.1 boards.
In addition , a example using the USB Host Wifi b/g/n/ac  dongle is welcome...

Waiting for get started examples...

Thanks
Br

**Comment by forg0ne** [comment]
Hi Br,
Unfortunately we don't have any examples on that platform.
However, it looks like this is an ARMv7-M platform.
We do have ports available for the ARMv7-M in the CPU, OS2, and OS3 repositories.
